### ISSUE TITLE
Adding bark to engraved blade craft does not work

### ISSUE THREAD

**Issue by PaperReaper** [Lothrazar/RootsClassic#113]
Minecraft version & Mod Version:
1.20.1, Forge 47.3.10, RootsClassic-1.20.1-1.4.1.jar

Single player or Server:
Private Server

Describe problem (what you were doing / what happened):
Adding bark to the engraved blade ritual does not work using the latest public build: RootsClassic-1.20.1-1.4.1.jar. 
I am trying to add 2 dark oak bark and 2 acasia bark to the crafting recipe. 
Removing the bark from braziers begins the craft without the modifiers. Seems to be a similar bug to one fixed yesterday https://github.com/Lothrazar/RootsClassic/issues/98

I am not a coder unfortunately, could anyone check if that is indeed the case?

Crash log (if any):
NA

**Comment by Mrbysco** [comment]
Do you have a screenshot of the setup? Or a video?
As I myself have yet to do more than craft a basic wand

**Comment by PaperReaper** [comment]
![2024-09-29_18 22 24](https://github.com/user-attachments/assets/04307316-ec6f-4226-9e5c-ae802840a8be)

I can also provide a recording if need be. The further 2 braziers have the golden carrot and apple while the ones around the altar have the bark in them (the braziers in the second screenshot are lit)
![2024-09-29_18 23 02](https://github.com/user-attachments/assets/28621ae3-89a1-486c-8547-9209c06c9f88)

**Comment by bobjegers** [comment]
I'll plug [my comment](https://github.com/Lothrazar/RootsClassic/issues/98#issuecomment-1789970094) on #98 as I also suspect it's related to this issue.

**Comment by PaperReaper** [comment]
As a temporary measure while this gets fixed, what would be the syntax for a command to spawn in an engraved blade with extra parameters?

**Comment by quat1024** [comment]
Ok, so the fundamental problem is: 

* the engraved blade recipe doesn't include any bark items in it, 
* but `RitualEngravedSword#doEffect` looks for bark items on lit incense braziers to decide what effects to apply,
* but this code can never be called, because the recipe will never match if there are any bark items on it.

I think there are two solutions:
* Just add bark to the incense list of this recipe. There is a limit of 4 barks, so this might not actually be a *terrible* idea; you'd need four copies of the recipe including 0, 1, 2, 3, and 4 copies of the `#rootsclassic:barks` ingredient.
* Allow ritual effects to drive the ritual recipe matching process a little bit. Basically the engraved blade ritual should pretend bark items don't exist, when checking if its own incense items match.

This also applies to the Crystal Staff imbuing recipe match problem. The current hotfix (allow all recipes with no incenses to match any set of incenses) isn't very good, since now the recipe will happily eat any items you burn as incense even if they're not spell powder.

And it also applies to the Time Shift ritual; it'll only ever work with one clock, but it's intended to work "proportional to the number of clocks".
